defmodule Fact.IndexFileReader do
  @moduledoc """
  Provides simple, **lazy streaming access** to event ids stored in index files.

  This module is responsible for reading event ids in either **forward** or **backward** order from index files 
  generated by the event ledger and indexers. Each event ID is a 32-character base16-encoded UUID without dashes.
  """

  @event_id_length 32

  @doc """
  Returns a lazy stream of event ids from the given index file in the order written.
    
  Forward reading uses buffered IO and is very efficient.
    
  ## Example
    
      iex> Fact.IndexFileReader.read_forward(".fact/indices/event_stream/customer-1234") |> Enum.take(1)
      ["2056f6d74fc043368b82464cf3229a21"]
    
  """
  def read_forward(path) do
    File.stream!(path) |> Stream.map(&String.slice(&1, 0, @event_id_length))
  end

  @doc """
  Returns a lazy stream of event ids from the given index file in the order written.
    
  See `Fact.IndexFileReader.Backwards.Line.read/1` for more details.
    
  ## Example
    
      iex> Fact.IndexFileReader.read_backward(".fact/indices/event_stream/customer-1234") |> Enum.take(1)
      ["4c4417b5b78740ffa764354434174c66"]
    
  """
  defdelegate read_backward(path), to: Fact.IndexFileReader.Backwards.Line, as: :read
end
