defmodule Fact.Storage.Driver.ContentAddressable do
  @moduledoc """
  A `Fact.Storage.Driver` implementation that uses a **content-addressable**
  strategy for generating record IDs.

  Instead of relying on an event-provided identifier, this driver computes a
  digest of the event’s encoded binary data. The resulting hash (hex-encoded)
  becomes the record ID which differs from the event ID. 

  By default, the driver uses the `:sha` hashing algorithm and computes the
  record ID length at compile time. The encoded hash is lowercase hexadecimal.
  """
  @behaviour Fact.Storage.Driver

  @hash_algorithm :sha
  @record_size :crypto.hash(@hash_algorithm, "") |> Base.encode16() |> String.length()

  @impl true
  @doc """
  Produces a content-addressable record ID by hashing the encoded event.

  ## Parameters

    * `event` — a map representing the event data.
    * `encode` — a function that takes the event and returns its binary
      representation (e.g., JSON, Msgpack, etc.).

  ## Returns

    A tuple `{record_id, encoded_event}` where:

    * `record_id` — the lowercase hex-encoded digest of the encoded event.
    * `encoded_event` — the binary produced by the `encode` function.

  ## Example

      iex> encode = fn evt -> :erlang.term_to_binary(evt) end
      iex> event = %{"foo" => "bar"}
      iex> {id, _data} = Fact.Storage.Driver.ContentAddressable.prepare_record(event, encode)
      iex> String.length(id)
      40   # SHA hex-encoded digest length

  """
  def prepare_record(event, encode) do
    encoded_event = encode.(event)
    event_id = :crypto.hash(@hash_algorithm, encoded_event) |> Base.encode16(case: :lower)
    {:ok, event_id, encoded_event}
  end

  @impl true
  @doc """
  Returns the fixed length of record IDs generated by this driver.

  The length is derived from the hex-encoded digest of the configured hash
  algorithm. It is computed at compile time for efficiency.

  ## Returns

    * an integer representing the record ID length

  """
  def record_id_length(), do: @record_size

  @impl true
  def record_size(), do: @record_size
end
